feat(pgs): initial support for conditional requests
picosh/pico pull request #178
Opened 2024-12-21 03:51 UTC by mac-chaffee

This PR (in theory) provides initial support for conditional requests.

I copied the important RFC-compliant bits from https://cs.opensource.google/go/go/+/refs/tags/go1.23.4:src/net/http/fs.go and used that to parse and set the right headers and status codes for conditional requests.

The alternative would be using `http.ServeContent`, but that requires an `io.ReadSeeker` which wouldn't work with files obtained from imgproxy since that returns an `io.ReadCloser`.

Ref: #177

### TODO

* I'm getting weird behavior between Souin and pgs/web, where sometimes it's just ignoring the `If-Modified-Since/If-None-Match` headers. Still need to debug that.

2024-12-21 15:35 UTC, mac-chaffee commented
To test, follow the new instructions in dev.md to sign up and upload a file. Then:

```
# This example hits pgs/web directly since the file isn't cached

$ curl -iH "Host: picouser-test.pgs.dev.pico.sh" -H "If-Modified-Since: Sat, 21 Dec 2026 03:03:03 GMT" -H 'If-None-Match: "a9a83095955b3d3efacc7f833a103cb2-1"'  localhost:3000/file.txt
HTTP/1.1 304 Not Modified
Cache-Control: max-age=600
Cache-Status: Souin; fwd=uri-miss; key=GET-http-picouser-test.pgs.dev.pico.sh-/file.txt; detail=UNCACHEABLE-STATUS-CODE
Etag: "a9a83095955b3d3efacc7f833a103cb2-1"
Surrogate-Key: picouser-test
Date: Sat, 21 Dec 2024 15:33:53 GMT

# Cache the file
$ curl -iH "Host: picouser-test.pgs.dev.pico.sh"  localhost:3000/file.txt
HTTP/1.1 200 OK
Cache-Control: max-age=600
Cache-Status: Souin; fwd=uri-miss; stored; key=GET-http-picouser-test.pgs.dev.pico.sh-/file.txt
Content-Length: 14
Content-Type: text/plain
Etag: "a9a83095955b3d3efacc7f833a103cb2-1"
Last-Modified: Sat, 21 Dec 2024 03:03:10 GMT
Surrogate-Key: picouser-test
Date: Sat, 21 Dec 2024 15:34:31 GMT

Hello, World!

# Now test conditional requests coming from souin
$ curl -iH "Host: picouser-test.pgs.dev.pico.sh" -H "If-Modified-Since: Sat, 21 Dec 2026 03:03:03 GMT" -H 'If-None-Match: "a9a83095955b3d3efacc7f833a103cb2-1"'  localhost:3000/file.txt
HTTP/1.1 304 Not Modified
Age: 63
Cache-Control: max-age=600
Cache-Status: Souin; hit; ttl=537; key=GET-http-picouser-test.pgs.dev.pico.sh-/file.txt; detail=OTTER
Date: Sat, 21 Dec 2024 15:34:31 GMT
Etag: "a9a83095955b3d3efacc7f833a103cb2-1"
Last-Modified: Sat, 21 Dec 2024 03:03:10 GMT
Surrogate-Key: picouser-test
```

2024-12-30 21:12 UTC, neurosnap commented
Thanks so much for your contribution!  I think we might want to take a stab at getting `http.ServeContent` to work with `pobj`.  I know this can get tricky so I can try to see how feasible it is.

2024-12-30 21:24 UTC, neurosnap commented
Alright, I quickly looked into it, I think we should just continue with your approach because converting `io.ReadCloser` to `io.ReadSeeker` might be prohibitive.

2024-12-30 21:26 UTC, mac-chaffee commented
Right If you update `pobj` to always return a `ReadSeeker`, we still couldn't use `http.ServeContent` in `pgs` because the file returned from imgproxy doesn't come through `pobj`; it comes from [`http.Get`](https://pkg.go.dev/net/http#Get).

2024-12-30 21:27 UTC, neurosnap requested changes
Overall looks good since most of the changes are from `fs.go`.

How hard would it be to add a test to `web_test.go` that ensures things are working as intended?

2024-12-30 21:27 UTC, neurosnap commented on pgs/fs.go
> +func setLastModified(w http.ResponseWriter, modtime time.Time) {
Do we need this fn?

2024-12-30 21:45 UTC, mac-chaffee commented
Sure I can work on a test, thanks for reviewing!

2024-12-31 01:42 UTC, mac-chaffee commented
Tests added!

2024-12-31 19:50 UTC, neurosnap approved these changes
Looks great, thanks!

2024-12-31 19:50 UTC, merged